package com.mall.furniture.mapper;

import com.mall.furniture.model.FurnitureCategory;
import com.mall.furniture.model.example.FurnitureCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FurnitureCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     */
    long countByExample(FurnitureCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     */
    int deleteByExample(FurnitureCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     */
    int insert(FurnitureCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     */
    int insertSelective(FurnitureCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FurnitureCategory selectOneByExample(FurnitureCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FurnitureCategory selectOneByExampleSelective(@Param("example") FurnitureCategoryExample example, @Param("selective") FurnitureCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<FurnitureCategory> selectByExampleSelective(@Param("example") FurnitureCategoryExample example, @Param("selective") FurnitureCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     */
    List<FurnitureCategory> selectByExample(FurnitureCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FurnitureCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") FurnitureCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     */
    FurnitureCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FurnitureCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FurnitureCategory record, @Param("example") FurnitureCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FurnitureCategory record, @Param("example") FurnitureCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FurnitureCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FurnitureCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") FurnitureCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}