package com.mall.furniture.mapper;

import com.mall.furniture.model.FurnitureGoods;
import com.mall.furniture.model.example.FurnitureGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FurnitureGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     */
    long countByExample(FurnitureGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     */
    int deleteByExample(FurnitureGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     */
    int insert(FurnitureGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     */
    int insertSelective(FurnitureGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FurnitureGoods selectOneByExample(FurnitureGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FurnitureGoods selectOneByExampleSelective(@Param("example") FurnitureGoodsExample example, @Param("selective") FurnitureGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FurnitureGoods selectOneByExampleWithBLOBs(FurnitureGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<FurnitureGoods> selectByExampleSelective(@Param("example") FurnitureGoodsExample example, @Param("selective") FurnitureGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     */
    List<FurnitureGoods> selectByExampleWithBLOBs(FurnitureGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     */
    List<FurnitureGoods> selectByExample(FurnitureGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FurnitureGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") FurnitureGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     */
    FurnitureGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FurnitureGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FurnitureGoods record, @Param("example") FurnitureGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FurnitureGoods record, @Param("example") FurnitureGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FurnitureGoods record, @Param("example") FurnitureGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FurnitureGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FurnitureGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FurnitureGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") FurnitureGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}