package com.mall.furniture.mapper;

import com.mall.furniture.model.FurnitureUser;
import com.mall.furniture.model.example.FurnitureUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FurnitureUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     */
    long countByExample(FurnitureUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     */
    int deleteByExample(FurnitureUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     */
    int insert(FurnitureUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     */
    int insertSelective(FurnitureUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FurnitureUser selectOneByExample(FurnitureUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FurnitureUser selectOneByExampleSelective(@Param("example") FurnitureUserExample example, @Param("selective") FurnitureUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<FurnitureUser> selectByExampleSelective(@Param("example") FurnitureUserExample example, @Param("selective") FurnitureUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     */
    List<FurnitureUser> selectByExample(FurnitureUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FurnitureUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") FurnitureUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     */
    FurnitureUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FurnitureUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FurnitureUser record, @Param("example") FurnitureUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FurnitureUser record, @Param("example") FurnitureUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FurnitureUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FurnitureUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") FurnitureUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}